### ISSUE TITLE
script:ox_lib] Unable to determine current resource version for 'illenium-appearance' 

### ISSUE THREAD

**Issue by OGGcallmedady** [iLLeniumStudios/illenium-appearance#404]
I installed it correctly, ensured ox lib before illenium-appearance. Its working perfectly just a message in console.

**Comment by harritvanbeek** [comment]
same here;

**Comment by TheiLLeniumStudios** [comment]
Read the docs again. You have downloaded the wrong thing.

**Comment by Max-Storm-03** [comment]
[resolved] Make sure you use the latest release and dont just click code to download. if you have done this just replace the resource and redo any config changes. https://github.com/iLLeniumStudios/illenium-appearance/releases/tag/v5.6.1

**Comment by Biserosbiss** [comment]
Gracias me sirvio mucho

**Comment by KingDmac** [comment]
> [resolved] Make sure you use the latest release and dont just click code to download. if you have done this just replace the resource and redo any config changes. https://github.com/iLLeniumStudios/illenium-appearance/releases/tag/v5.6.1

hey i did this over and over and keep getting that error still
is there another way to fix
